version: '3.8'

services:
  expense-tracker:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - expense_data:/app/data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: expense_tracker_app

volumes:
  expense_data: